### ISSUE TITLE
"--notice" parameter does not seem to work

### ISSUE THREAD

**Issue by jmckenna** [rectalogic/notify-irc#6]
- set `notice: true` for job
  - example run: https://github.com/MapServer/MapServer-documentation/pull/635/files
- IRC channel contained no updates at all
- assumption was that this setting would `Use NOTICE instead of PRIVMSG`
- using notify-irc@v1

**Comment by rectalogic** [comment]
Maybe your channel blocks NOTICE? Check the MODE settings

**Comment by jmckenna** [comment]
Not that I can see: `Mode : +nt-lk`

**Comment by jmckenna** [comment]
Could it be the `n` (Disallow messages from users who are not channel members entering the channel)  ?

**Comment by jmckenna** [comment]
Block notice seems to be `+T`

**Comment by jmckenna** [comment]
Can you point to an example mode settings for a channel, that works with notices, with irc.libera.chat ?

**Comment by rectalogic** [comment]
We used to use notice with freenode, but we don't even use IRC any more.
I just pushed a branch that adds a new `verbose` parameter so you might try that and see if you get any logs out of pydle.
https://github.com/rectalogic/notify-irc/tree/verbose

So in your workflow use `uses: rectalogic/notify-irc@verbose` and add `verbose: true` to the parameters.

Let me know if the verbose option works and I'll merge it into master.

**Comment by jmckenna** [comment]
Thanks.  Here is the run, which seems to say that the notice was sent properly: https://github.com/MapServer/MapServer-documentation/runs/4268402965?check_suite_focus=true
```
DEBUG:NotifyIRC:libera:>> NOTICE #mapserver :jmckenna opened PR https://github.com/MapServer/MapServer-documentation/pull/637
DEBUG:NotifyIRC:libera:>> NOTICE #mapserver :
DEBUG:NotifyIRC:libera:>> VERSION 
```
Sigh.  It could be my client, sure, (Thunderbird), but another channel member is not seeing the notices with another client.

Darn.  I'm not sure where the issue is.

Closing.
